s=imread('gameofsquaresend.png');
s(s < 128) = 0;
s(s > 127) = 1;
imshow(s)

%%
word_size = 3;
ram_size = 160*120;
%%

fileID = fopen('end.mif', 'wt');
fprintf( fileID, '%s\n', '-- Generated by mif_gen Matlab script');
fprintf( fileID, '%s\n\r\n', '-- FPGA SITE - https://fpgasite.wordpress.com');
fprintf( fileID, '%s%d%s\n\r', 'WIDTH=', word_size, ';');
fprintf( fileID, '%s%d%s\n\n\r', 'DEPTH=', ram_size, ';');
fprintf( fileID, '%s\n\r', 'ADDRESS_RADIX=UNS;');
fprintf( fileID, '%s\n\n\r', 'DATA_RADIX=UNS;');
fprintf( fileID, '%s\n\r', 'CONTENT BEGIN');

%transform a 3d matrix to 2d
for w=1:120
    for h=1:160
        value(w,h)=s(w,h,1)+2*s(w,h,2)+4*s(w,h,3);
    end
end

% write values to file
idx = 0;
for w=1:120
    for h = 1:160
        fprintf( fileID, '%d : %d; %s\r\n', idx, value(w,h));
        fprintf(fileID, '%s\r\n', '');
        idx = idx+1;
    end
end
fprintf( fileID, '%s\n\r', 'END;');

fclose( fileID);